### ISSUE TITLE
CMMVC7205E The command failed because it is not supported.

### ISSUE THREAD

**Issue by loopway** [IBM/ibm-block-csi-driver#717]
### Environment: 
IBM FlashSystem 5030 (8.5.0.11) connected with FC to three Bare-metal OpenShift Nodes (4.15.19) with IBM block storage CSI driver operator installed (1.11.3)

### Problem Description: 
New LUNs get created on storage system, but not mapped to hosts. See errors in logs below.

### Logs:
pod event:
 AttachVolume.Attach failed for volume "pvc-bdf5c3bf-a4d9-4bad-b7ee-3733b5184c20" : rpc error: code = Internal desc = CLI failure. Return code is 1. Error message is "b'CMMVC7205E The command failed because it is not supported.\n'"

ibm-block-csi-controller-0 log:
  2024-07-08 23:42:19,628 ERROR [140216497063680] [SVC:4;60050763808104F70800000000000035] (exception_handler.py:handle_exception:35) - CLI failure. Return code is 1. Error message is "b'CMMVC7205E The command failed because it is not supported.\n'"

host-definer-hostdefiner-59c7c7548c-fm7n7 log:
  ...
  2024-07-08 21:45:51,318 DEBUG [140352619017984] [Thread-9] (utils.py:get_node_id_info:48) - node name : ocp0, nvme_nqn: nqn.2014-08.org.nvmexpress:uuid:56f808db-dbc0-4c0d-8dbd-5d0a01120e69, fc_wwns : 51402ec01482c418:51402ec01482c41a:51402ec0110ecba4:51402ec0110ecba6, iscsi_iqn : iqn.1994-05.com.redhat:714b6fdda0da
  ...
  2024-07-08 21:45:51,744 ERROR [140352610625280] [Thread-10] (array_mediator_svc.py:_lsnvmefabric:988) - Failed to get nvme fabrics. Reason is: CLI failure. Return code is 1. Error message is "b'CMMVC7205E The command failed because it is not supported.\n'"

### Configuration
Even though we have set environment `CONNECTIVITY_TYPE = fc` on the host-definer-hostdefiner, it seems the CSI still tries to make a connection to the LUN over NVMEoverFC and that obviously fails - since its not available in our setup. 🏴‍☠️

**Comment by kasserater** [comment]
hi @loopway 
can you please share the hostdefiner custom resource YAML?
in that YAML, it should be enough to uncomment the `connectivityType:` field and set it to `fc`. is that what you did?
see https://raw.githubusercontent.com/IBM/ibm-block-csi-operator/v1.11.3/config/samples/csi_v1_hostdefiner_cr.yaml for a sample YAML that DOES NOT have the comment removed, so you can take that for comparison and perform the changes i mentioned above to resolve

**Comment by kasserater** [comment]
another option is to disable NVMe on the host side, as hostdefiner detects it and uses it by default, so disabling NVMe on the host will remove that option from the hostdefiner logic decision tree

**Comment by kasserater** [comment]
please see https://www.ibm.com/docs/en/stg-block-csi-driver/1.11.3?topic=configuring-host-definer

**Comment by loopway** [comment]
hi @kasserater 
thanks for your quick follow up. here's our host-definer spec:

```
...
spec:
  hostDefiner:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
    allowDelete: true
    connectivityType: fc
    dynamicNodeLabeling: true
    imagePullPolicy: IfNotPresent
    prefix: ocp-01_
    repository: quay.io/ibmcsiblock/ibm-block-csi-host-definer
    tag: 1.11.2
...
```

Is there a way to force FC only connections with the CSI? If not, we will try to disable the NVMe capabilities of the kernel driver on the hosts - which probably will require a reboot of the hosts...
