### ISSUE TITLE
PVC with accessMode ReadWriteMany has wrong permission/ownership

### ISSUE THREAD

**Issue by kbgorlun** [IBM/ibm-block-csi-driver#780]
OpenShift version 4.18.0-okd-scos.7 on BareMetal
Update channel stable-scos-4
OS-IMAGE CentOS Stream CoreOS 418.9.202503240632-0
KERNEL-VERSION 5.14.0-573.el9.x86_64
ibm-block-csi-driver v1.12.2

If we use a PVC with accessMode ReadWriteOnce, everything works as expected when using a single replica.
The manifest used for the PVC and Deployment:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-rwo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-writer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-writer
  template:
    metadata:
      labels:
        app: my-writer
    spec:
      containers:
      - name: writer-container
        image: busybox:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          while true; do
            echo "$(date) - Writing from $(hostname)" >> /mnt/data/shared-log.txt
            sleep 5
          done
        volumeMounts:
        - name: rwo-storage
          mountPath: /mnt/data
      volumes:
      - name: rwo-storage
        persistentVolumeClaim:
          claimName: my-rwo-pvc
```

```
$ oc get po
NAME                            READY   STATUS    RESTARTS   AGE
my-writer-app-7584796d5-5fzgr   1/1     Running   0          42s

$ oc exec -it my-writer-app-7584796d5-5fzgr -- sh -c "id;ls -ld /mnt/data;tail -3 /mnt/data/shared-log.txt"
uid=1000870000(1000870000) gid=0(root) groups=0(root),1000870000
drwxrwsr-x    3 root     1000870000      4096 Apr 11 11:14 /mnt/data
Fri Apr 11 11:15:18 UTC 2025 - Writing from my-writer-app-7584796d5-5fzgr
Fri Apr 11 11:15:23 UTC 2025 - Writing from my-writer-app-7584796d5-5fzgr
Fri Apr 11 11:15:28 UTC 2025 - Writing from my-writer-app-7584796d5-5fzgr
```

We delete and change the PVC to ReadWriteMany and Deployment to 2 replicas. The permission
and ownership is wrong:

```
$ oc logs -l app=my-writer | tail -1
/bin/sh: can't create /mnt/data/shared-log.txt: Permission denied

$ oc get po
NAME                             READY   STATUS    RESTARTS   AGE
my-writer-app-7f7f7688db-zctsh   1/1     Running   0          94s
my-writer-app-7f7f7688db-zrm9g   1/1     Running   0          96s

$ oc exec -it my-writer-app-7f7f7688db-zctsh -- sh -c "id;ls -ld /mnt/data"
uid=1000870000(1000870000) gid=0(root) groups=0(root),1000870000
drwxr-xr-x    3 root     root          4096 Apr 11 11:03 /mnt/data

$ oc exec -it my-writer-app-7f7f7688db-zrm9g -- sh -c "id;ls -ld /mnt/data"
uid=1000870000(1000870000) gid=0(root) groups=0(root),1000870000
drwxr-xr-x    3 root     root          4096 Apr 11 11:03 /mnt/data
```

Also tried with accessModes ReadWriteOnce + ReadWriteMany, and we get this problem instead:

```
$ oc get po
NAME                            READY   STATUS    RESTARTS   AGE
my-writer-app-5c85744b5-7j4j9   1/1     Running   0          92s
my-writer-app-5c85744b5-8s98s   1/1     Running   0          12s

$ oc exec -it my-writer-app-5c85744b5-7j4j9 -- sh -c "id;ls -ld /mnt/data;tail -5 /mnt/data/shared-log.txt"
uid=1000870000(1000870000) gid=0(root) groups=0(root),1000870000
drwxrwsr-x    3 root     1000870000      4096 Apr 11 11:29 /mnt/data
Fri Apr 11 11:31:17 UTC 2025 - Writing from my-writer-app-5c85744b5-7j4j9
Fri Apr 11 11:31:22 UTC 2025 - Writing from my-writer-app-5c85744b5-7j4j9
Fri Apr 11 11:31:27 UTC 2025 - Writing from my-writer-app-5c85744b5-7j4j9
Fri Apr 11 11:31:32 UTC 2025 - Writing from my-writer-app-5c85744b5-7j4j9
Fri Apr 11 11:31:37 UTC 2025 - Writing from my-writer-app-5c85744b5-7j4j9

$ oc exec -it my-writer-app-5c85744b5-8s98s -- sh -c "id;ls -ld /mnt/data;tail -5 /mnt/data/shared-log.txt"
uid=1000870000(1000870000) gid=0(root) groups=0(root),1000870000
drwxrwsr-x    3 root     1000870000      4096 Apr 11 11:29 /mnt/data
Fri Apr 11 11:31:25 UTC 2025 - Writing from my-writer-app-5c85744b5-8s98s
Fri Apr 11 11:31:30 UTC 2025 - Writing from my-writer-app-5c85744b5-8s98s
Fri Apr 11 11:31:35 UTC 2025 - Writing from my-writer-app-5c85744b5-8s98s
Fri Apr 11 11:31:40 UTC 2025 - Writing from my-writer-app-5c85744b5-8s98s
Fri Apr 11 11:31:45 UTC 2025 - Writing from my-writer-app-5c85744b5-8s98s
```

It is using the same PV, but the writes are only from the same pod..
During the testing I have seen some writes from other pod, but not on this last run.

Please let me know if you need any more information.

Thanks,
Göran
